# Generated by Django 5.0.3 on 2024-03-13 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_name_profile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
